config/routes.rb
Sunrise::Application.routes.draw do
  get "transactions/index"
  resources :accounts, only: :index
  resources :bids, only: [:create, :index, :new]
  devise_for :users
  root 'bids#index'

end

app/models/account.rb
class Account < ActiveRecord::Base
  belongs_to :user
  has_many :in_transactions, class_name: 'Transaction', foreign_key: :to_id
  has_many :out_transactions, class_name: 'Transaction', foreign_key: :from_id

  before_create :add_demo_money_in_production

  def add_demo_money_in_production
    if Rails.env.production?
    	case currency
    	when 'btc'
    		self.amount = 10
    	when 'usd'
    		self.amount = 1000
    	when 'eur'
    		self.amount = 500
    	end
    end
  end

end

app/models/bid.rb
class Bid < ActiveRecord::Base
  belongs_to :user
  validates :buy_currency, :sell_currency, :amount, :max_price, presence: true
  validate :user_have_sufficient_funds
  validate :currencies_in_available_currencies
  validate :currencies_not_same

  before_create :calculate

  def account_buy
    user.accounts.where(currency: buy_currency).first
  end

  def account_sell
    user.accounts.where(currency: sell_currency).first
  end

  def done! closing_price = max_price
    self.state = 'done'
    ActiveRecord::Base.connection.execute(
      "UPDATE accounts SET amount = amount - #{closing_price} WHERE id = #{account_sell.id}")
    ActiveRecord::Base.connection.execute(
      "UPDATE accounts SET amount = amount + #{amount} WHERE id = #{account_buy.id}")
    self.info += "Bid closed with price: #{closing_price}" # TODO transactions log
    save!
  end

  def partially_done! foreign_amount, foreign_price
    self.amount    -= foreign_price
    self.max_price -= foreign_amount
    ActiveRecord::Base.connection.execute(
      "UPDATE accounts SET amount = amount - #{foreign_amount} WHERE id = #{account_sell.id}")
    ActiveRecord::Base.connection.execute(
      "UPDATE accounts SET amount = amount + #{foreign_price} WHERE id = #{account_buy.id}")
    save!
  end

  def user_have_sufficient_funds
    # TODO funds reservation and validation through all bids
    account = user.accounts.find_by(currency: sell_currency)
    if account.nil? or account.amount < max_price
      errors.add :max_price, 'not enough funds'
    end
  end

  def currencies_in_available_currencies
    errors.add(:buy_currency, 'unknown currency') unless Rails.configuration.currencies.include? buy_currency
    errors.add(:sell_currency, 'unknown currency') unless Rails.configuration.currencies.include? sell_currency
  end

  def currencies_not_same
    if sell_currency == buy_currency
      errors.add :buy_currency, 'currency same as sell'
      errors.add :sell_currency, 'currency same as buy'
    end
  end

  def calculate
    self.rate = max_price/amount
    self.reverse_rate = amount/max_price
  end

end

app/models/transaction.rb
class Transaction < ActiveRecord::Base
  belongs_to :from, class_name: 'Account'
  belongs_to :to, 	class_name: 'Account'
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :bids
  has_many :accounts


  after_create :create_user_accounts

  def create_user_accounts
  	Rails.configuration.currencies.each do |c|
  		accounts.create currency: c
  	end
  end

  Rails.configuration.currencies.each do |c|
    define_method(c) { accounts.find_by(currency: c) }
  end

end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!

  # GET /accounts
  # GET /accounts.json
  def index
    @accounts = current_user.accounts
  end

  # GET /accounts/1
  # GET /accounts/1.json
  def show
  end

  # GET /accounts/new
  def new
    @account = Account.new
  end

  # GET /accounts/1/edit
  def edit
  end

  # POST /accounts
  # POST /accounts.json
  def create
    @account = Account.new(account_params)

    respond_to do |format|
      if @account.save
        format.html { redirect_to @account, notice: 'Account was successfully created.' }
        format.json { render action: 'show', status: :created, location: @account }
      else
        format.html { render action: 'new' }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accounts/1
  # PATCH/PUT /accounts/1.json
  def update
    respond_to do |format|
      if @account.update(account_params)
        format.html { redirect_to @account, notice: 'Account was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1
  # DELETE /accounts/1.json
  def destroy
    @account.destroy
    respond_to do |format|
      format.html { redirect_to accounts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account
      @account = Account.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def account_params
      params.require(:account).permit(:currency, :amount, :reserved, :user_id)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bids_controller.rb
class BidsController < ApplicationController
  before_action :set_bid, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, only: [:new, :create]

  # GET /bids
  # GET /bids.json
  def index
    @bids = Bid.order('created_at DESC').page params[:page]
  end

  # GET /bids/1
  # GET /bids/1.json
  def show
  end

  # GET /bids/new
  def new
    @bid = Bid.new
  end

  # GET /bids/1/edit
  def edit
  end

  # POST /bids
  # POST /bids.json
  def create
    @bid = current_user.bids.build(bid_params)

    respond_to do |format|
      if @bid.save
        format.html { redirect_to bids_path, notice: 'Bid was successfully created.' }
        format.json { render action: 'show', status: :created, location: @bid }
      else
        format.html { render action: 'new' }
        format.json { render json: @bid.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bids/1
  # PATCH/PUT /bids/1.json
  def update
    respond_to do |format|
      if @bid.update(bid_params)
        format.html { redirect_to @bid, notice: 'Bid was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @bid.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bids/1
  # DELETE /bids/1.json
  def destroy
    @bid.destroy
    respond_to do |format|
      format.html { redirect_to bids_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bid
      @bid = Bid.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bid_params
      params.require(:bid).permit(:buy_currency, :sell_currency, :amount, :max_price)
    end
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
  def show
  	@user = current_user
  	halt if @user.nil?
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  def index
  	@transactions = Transaction.order('id DESC').page params[:page]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/accounts/_form.html.slim
= simple_form_for @account, :html => { :class => "form-horizontal" } do |f|
  = f.input :currency
  = f.input :amount
  = f.input :reserved
  = f.input :user_id
  .form-actions
    = f.button :submit, :class => 'btn-primary'
    '
    = link_to t('.cancel', :default => t("helpers.links.cancel")), accounts_path, :class => 'btn'

app/views/accounts/edit.html.slim
- model_class = Account
div class="page-header"
  h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/accounts/index.html.slim
- model_class = Account
div class="page-header"
  h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
table class="table table-striped"
  thead
    tr
      th= model_class.human_attribute_name(:id)
      th= model_class.human_attribute_name(:currency)
      th= model_class.human_attribute_name(:amount)
      th
  tbody
    - @accounts.each do |account|
      tr
        td= account.id
        td= account.currency
        td= account.amount
        td
          = link_to 'Add funds', '#', :class => 'btn btn-mini'
          '
          = link_to 'Withdraw', '#', :class => 'btn btn-mini btn-danger'

app/views/accounts/new.html.slim
- model_class = Account
div class="page-header"
  h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/accounts/show.html.slim
- model_class = Account
div class="page-header"
  h1=t '.title', :default => model_class.model_name.human.titleize

p
  strong= model_class.human_attribute_name(:currency) + ':'
  br
  = @account.currency
p
  strong= model_class.human_attribute_name(:amount) + ':'
  br
  = @account.amount
p
  strong= model_class.human_attribute_name(:reserved) + ':'
  br
  = @account.reserved
p
  strong= model_class.human_attribute_name(:user_id) + ':'
  br
  = @account.user_id

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), accounts_path, :class => 'btn'
  '
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_account_path(@account), :class => 'btn'
  '
  = link_to t('.destroy', :default => t("helpers.links.destroy")), account_path(@account), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'

app/views/bids/_form.html.slim
= simple_form_for @bid, :html => { :class => "form-horizontal" } do |f|
  = f.input :buy_currency, collection: Rails.configuration.currencies
  = f.input :amount
  = f.input :sell_currency, collection: Rails.configuration.currencies
  = f.input :max_price
  .form-actions
    = f.button :submit, :class => 'btn-primary'
    '
    = link_to t('.cancel', :default => t("helpers.links.cancel")), bids_path, :class => 'btn'

app/views/bids/edit.html.slim
- model_class = Bid
div class="page-header"
  h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/bids/index.html.slim
- model_class = Bid
div class="page-header"
  h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
table class="table table-striped"
  thead
    tr
      th= model_class.human_attribute_name(:id)
      th= model_class.human_attribute_name(:buy_currency)
      th= model_class.human_attribute_name(:amount)
      th= model_class.human_attribute_name(:sell_currency)
      th= model_class.human_attribute_name(:max_price)
      th= model_class.human_attribute_name(:rate)
      th= model_class.human_attribute_name(:reverse_rate)
      th= model_class.human_attribute_name(:state)
      th= model_class.human_attribute_name(:user_id)
      th= model_class.human_attribute_name(:created_at)
  tbody
    - @bids.each do |bid|
      tr
        td= bid.id
        td= bid.buy_currency
        td= bid.amount
        td= bid.sell_currency
        td= bid.max_price
        td
          a href="#" data-toggle="tooltip" title="Хочу купить #{bid.buy_currency} за #{bid.sell_currency} по #{bid.rate} #{bid.sell_currency} за 1 #{bid.buy_currency}"
            = bid.rate
        td= bid.reverse_rate
        td= bid.state
        td= bid.user_id
        td= bid.created_at.to_i

p= link_to t('.new', :default => t("helpers.links.new")), new_bid_path, :class => 'btn btn-primary'
p= paginate @bids

app/views/bids/new.html.slim
- model_class = Bid
div class="page-header"
  h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/bids/show.html.slim
- model_class = Bid
div class="page-header"
  h1=t '.title', :default => model_class.model_name.human.titleize

p
  strong= model_class.human_attribute_name(:what) + ':'
  br
  = @bid.what
p
  strong= model_class.human_attribute_name(:for) + ':'
  br
  = @bid.for
p
  strong= model_class.human_attribute_name(:count) + ':'
  br
  = @bid.count
p
  strong= model_class.human_attribute_name(:price) + ':'
  br
  = @bid.price
p
  strong= model_class.human_attribute_name(:rate) + ':'
  br
  = @bid.rate
p
  strong= model_class.human_attribute_name(:reverse_rate) + ':'
  br
  = @bid.reverse_rate
p
  strong= model_class.human_attribute_name(:user_id) + ':'
  br
  = @bid.user_id

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), bids_path, :class => 'btn'
  '
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_bid_path(@bid), :class => 'btn'
  '
  = link_to t('.destroy', :default => t("helpers.links.destroy")), bid_path(@bid), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'

app/views/layouts/application.html.slim
doctype html
html lang="en"
  head
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    title= content_for?(:title) ? yield(:title) : "Sunrise"
    = csrf_meta_tags

    /! Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'



  body
    .navbar.navbar-fixed-top
      .navbar-inner
        .container
          a.btn.btn-navbar data-target=".nav-collapse" data-toggle="collapse"
            span.icon-bar
            span.icon-bar
            span.icon-bar
          a.brand href="/" Sunrise
          .container.nav-collapse
            ul.nav
              li= link_to "Accounts", main_app.accounts_path
              li= link_to "Bids", main_app.bids_path
            /ul.nav.pull-right
              li= link_to 'Profile', '/profile'

    .container

      .row
        .span12
          = bootstrap_flash
          = yield
        /.span3
          .well.sidebar-nav
            h3 Sidebar
            ul.nav.nav-list
              li.nav-header Sidebar
              li= link_to "Link 1", "/path1"
              li= link_to "Link 2", "/path2"
              li= link_to "Link 3", "/path3"

      footer
        p &copy; Vasya Dotcom 2013. Powered by Sunrise Engine.
    /!
      Javascripts
      \==================================================
    /! Placed at the end of the document so the pages load faster
    = javascript_include_tag "application"

app/views/transactions/index.html.slim
- model_class = Transaction
div class="page-header"
  h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
table class="table table-striped"
  thead
    tr
      th= model_class.human_attribute_name(:id)
      th= model_class.human_attribute_name(:from_id)
      th= model_class.human_attribute_name(:to_id)
      th= model_class.human_attribute_name(:bids)
      th= model_class.human_attribute_name(:amount)
  tbody
    - @transactions.each do |t|
      tr
        td= t.id
        td= t.from_id
        td= t.to_id
        td= t.bids
        td= t.amount
= paginate @transactions